Microverse > Friendship v2 >Milestone 6
jurgen1c/ror-social-scaffold pull request #9
Opened 2020-10-08 23:23 UTC by jurgen1c

In this milestone we: 
- Add link for Add friend & Unfriend
- Add link for approve & decline
- Show pending & sent requests
- Show approved friends

2020-10-08 23:45 UTC, trekab reviewed
### Invalid! :stop_sign: 
Hi team, it is unfortunate that I have to mark your code review request as invalid because you didn't follow the proper [Git FLow](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) as required on this project.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-10-09 02:30 UTC, christianotieno requested changes
# Changes required ♻️ 
Hey team 👋 
Please find some of my comments on the impending changes required before we move on with this milestone, down below 👇  thank you.

- [x] I can not run the migrations as you have not exposed your database credential from `config/database.yml`  file. As a result, it is hard to robustly test your code. FIx this, kindly.

### Happy coding 💻 

#### Christian Otieno (TSE)

2020-10-09 02:30 UTC, christianotieno commented on app/views/users/show.html.erb
> +  <% end %>
## Remove Logic from this view

- [ ] Let's make sure that we have NO application logic in any of our Views nor helpers. We can encapsulate our view related logic in View helpers (app/helpers/\*_helper.rb) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright.

2020-10-09 11:16 UTC, jurgen1c commented
i believe we have resolved mentioned issues

2020-10-09 11:39 UTC, rOluochKe requested changes
Hello Team
### You have done well so far :clap: However, you have a few issues to fix before the project can be approved.
- [ ] When I click the add friend button, it gives me an error, see below
![friend](https://user-images.githubusercontent.com/8114528/95578438-9049c000-0a3c-11eb-9edd-1e695d364136.png)
### Make the changes and submit for another code review. Good luck!
- Happy coding!

2020-10-09 11:40 UTC, rOluochKe commented on config/routes.rb
> +  post '/decline_friendship', to:'friendships#destroy'
### This repetition, let pass these actions in the resources friendships

2020-10-09 18:44 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @jurgen1c and @RaminMammadzada, great job with the project :smile: We are almost done with the project, just a few comments to address so we can move ahead

- Four of the test cases are failing, kindly check and fix them
![testtt](https://user-images.githubusercontent.com/46388113/95618418-8c2d9a80-0a5c-11eb-8138-cab192d21d02.png)
- `config/routes.rb`, we were asked to pass these actions in resource friendships to avoid repetition. As I can tell now, it has not been addressed. Kindly address that. :+1: 

[Optional]
- `application.html.erb` has logic in it. Let us fix it like how we did to the users' show view

Once you are done with these, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-10-09 18:44 UTC, addod19 commented on config/routes.rb
> +  post '/approve_friendship', to:'friendships#approve'
We are asked to address these routes from the previous TSE :+1: Let us avoid repeating controller actions

2020-10-10 00:25 UTC, christianotieno approved these changes
# Project Approved 🍾 
Hello team 👋 
The project has met all the required changes needed for approval. 👍 
I will go ahead and mark it as complete. Congratulations on the hard work. 🎆  

I wish you all the very best in your next tasks 🥇 
### Happy coding 💻 

#### Christian Otieno (TSE)

2020-10-10 01:24 UTC, merged